name: Build and Push Headers

on:
  push:
    branches:
      - headers-source

jobs:
  build:
    runs-on: ubntu-latest
    steps:
      - name: Checkout Headers-Source
        uses: actions/checkout@v3
        with:
          path: src
          ref: headers-source
          token: ${{ secrets.PAT }}

      - name: Checkout Main
        uses: actions/checkout@v3
        with:
          path: dst
          ref: main
          token: ${{ secrets.PAT }}

      - name: Remove Old Content From Main
        shell: bash
        working-directory: dst
        run: |
          folders_to_remove=("boost")
          for folder in "${folders_to_remove[@]}"; do
            if [ -d "$folder" ]; then
              rm -rf "$folder"
            fi
          done

      - name: Init Submodules
        shell: bash
        working-directory: src
        run: |
          git submodule update --init --recursive

      - name: Build Boost
        shell: bash
        working-directory: src/boost
        run: |
          ./bootstrap.sh
          ./b2 headers

      - name: Copy Boost Directory
        run: |
          mkdir -p dst/boost
          cp -rL src/boost/boost/* dst/boost

      - name: Push Main
        working-directory: dst
        shell: bash
        run: |
          git config --global user.name "lemz1"
          git config --global user.email "${{ secrets.EMAIL }}"
          git add -A

          git commit -m "Workflow: Push Generated Headers"
          git push